package manual

// Chapter represents an individual section of the Starfleet Technical Manual.
type Chapter struct {
	ID       string   // Unique identifier (e.g. "combat", "nav")
	Number   int      // 1-indexed chapter number (1..8)
	Title    string   // Full chapter title (e.g. "Weapons & Combat")
	ShortTag string   // Sidebar label (e.g. "[3] COMBAT")
	Lines    []string // Pre-formatted lines wrapped to <= 43 characters
}

func defaultChapters() []Chapter {
	return []Chapter{
		{
			ID:       "systems",
			Number:   1,
			Title:    "Systems & Subsystems",
			ShortTag: "[1] SYSTEMS",
			Lines: []string{
				"1. PRIMARY VESSEL SUBSYSTEMS",
				"─────────────────────────────────────────",
				"The USS Enterprise (NCC-1701) is equipped",
				"with 8 vital operating systems:",
				"",
				"• [WARP] Warp Engines: Faster-than-light",
				"  propulsion across quadrants & sectors.",
				"• [SRS] Short-Range Sensors: Scans the",
				"  immediate 8x8 sector grid.",
				"• [LRS] Long-Range Sensors: Scans adjacent",
				"  3x3 quadrants for hostiles & bases.",
				"• [PHA] Phaser Controls: Beam weapons",
				"  drawing directly from main energy.",
				"• [TOR] Photon Tubes: Torpedo launcher",
				"  with onboard magazine of 10 tubes.",
				"• [DAM] Damage Control: System diagnostics",
				"  and automated repair tracking.",
				"• [SHL] Deflector Shields: Energy barrier",
				"  mitigating direct hull damage.",
				"• [COM] Library Computer: Astrogation,",
				"  galactic charts, and target tracking.",
				"",
				"2. CASUALTY & DAMAGE EFFECTS",
				"─────────────────────────────────────────",
				"System damage counts down in stardates.",
				"When damaged (> 0.0 SD):",
				"• SRS: Sector display is blind/jammed.",
				"• LRS: Adjacent quadrant scans black out.",
				"• PHA: Energy discharges become erratic.",
				"• TOR: Launcher mechanism jams.",
				"• COM: Galactic Chart and auto-nav fail.",
				"• WARP: FTL flight restricted to impulse.",
				"• SHL: Shield deflection drops to 0%.",
				"",
				"3. LIFE SUPPORT & ALERT STATES",
				"─────────────────────────────────────────",
				"• GREEN: No immediate hostiles detected.",
				"• YELLOW: Hostiles within sensor sweep.",
				"• RED: Combat active or shields down.",
				"• DOCKED: Moored adjacent to starbase.",
				"  Accelerated 4x repairs & full restock.",
				"Energy reserves drop continuously. If main",
				"power hits 0, life support terminates.",
			},
		},
		{
			ID:       "nav",
			Number:   2,
			Title:    "Flight Mechanics & Navigation",
			ShortTag: "[2] NAVIGATION",
			Lines: []string{
				"1. ASTROGATION COORDINATE GRID",
				"─────────────────────────────────────────",
				"The galaxy is structured on a dual grid:",
				"",
				"• Galaxy: 8x8 Quadrants (Row 1-8, Col 1-8)",
				"• Sector: 8x8 Local Sectors (R 1-8, C 1-8)",
				"",
				"Current location displays as Q[r,c] S[r,c].",
				"",
				"Galactic Star Chart (C / chart) notation:",
				"• ···  Unexplored quadrant (unscanned)",
				"• .1.  Known Starbase reported by Command",
				"• KBS  3-digit scan: Klingons/Bases/Stars",
				"",
				"2. PROPULSION & VECTOR FLIGHT",
				"─────────────────────────────────────────",
				"Astrogation accepts course headings in",
				"radians (0.0 to 6.28) or sector jumps:",
				"",
				"• 0.00 / 6.28 = East   (+C)",
				"• 1.57 (π/2)  = North  (-R)",
				"• 3.14 (π)    = West   (-C)",
				"• 4.71 (3π/2) = South  (+R)",
				"",
				"Navigation Syntax:",
				"  nav <course> <warp>",
				"  nav q <quad-row> <quad-col>",
				"  nav s <sect-row> <sect-col>",
				"",
				"3. POWER CONSUMPTION & EQUATIONS",
				"─────────────────────────────────────────",
				"Distance formula:",
				"  D = sqrt((ΔR)^2 + (ΔC)^2)",
				"Energy required:",
				"  E = 2 * Distance * WarpFactor",
				"*Raised shields double fuel consumption!*",
				"",
				"4. STELLAR & TACTICAL HAZARDS",
				"─────────────────────────────────────────",
				"• Stars (*): Solid obstacles; block flight.",
				"• Planets (@): Planetary mass; blocks warp.",
				"• Black Holes: Extreme gravity wells that",
				"  pull torpedoes and trap starships.",
			},
		},
		{
			ID:       "combat",
			Number:   3,
			Title:    "Weapons & Combat Mathematics",
			ShortTag: "[3] COMBAT",
			Lines: []string{
				"1. PHOTON TORPEDOES",
				"─────────────────────────────────────────",
				"Ballistic projectiles launched along an",
				"exact vector using 40-step ray tracing.",
				"Torpedoes detonate upon collision with any",
				"solid obstacle, vessel, or quadrant edge.",
				"",
				"• Maximum complement: 10 torpedoes",
				"• Damage: 800 - 1200 units (lethal hit)",
				"• Command syntax:",
				"    tor <course>",
				"    tor <sect-row> <sect-col>",
				"",
				"2. PHASER ARRAYS",
				"─────────────────────────────────────────",
				"High-energy beam weapons dividing fired",
				"charge across all hostiles in quadrant.",
				"Phaser attenuation formula:",
				"    Damage = Energy / (Distance * Factor)",
				"Where Factor accounts for sensor range.",
				"Phasers never miss, but damage diminishes",
				"rapidly over long sector distances.",
				"• Command syntax:",
				"    pha <energy-units>",
				"",
				"3. TACTICAL TARGET-LOCK HUD",
				"─────────────────────────────────────────",
				"Starfleet fire-control computer computes",
				"ideal torpedo angles and phaser telemetry.",
				"• Press [T] or click target to lock.",
				"• Shows bearing, distance, and hit chance.",
			},
		},
		{
			ID:       "shields",
			Number:   4,
			Title:    "Deflector Shields & Damage Control",
			ShortTag: "[4] SHIELDS",
			Lines: []string{
				"1. DEFLECTOR SHIELD MECHANICS",
				"─────────────────────────────────────────",
				"Deflector shields form an energy perimeter",
				"absorbing enemy disruptor & torpedo fire.",
				"",
				"• Transfer Energy: she <units>",
				"  Positive value diverts power to shields.",
				"  Negative value returns shield energy.",
				"• Maximum shield capacity: 2500 units.",
				"• Absorption Efficiency: Raised shields",
				"  absorb hits. If shields buckle to 0,",
				"  excess energy penetrates hull armor.",
				"",
				"2. HULL BREACHES & CREW CASUALTIES",
				"─────────────────────────────────────────",
				"Direct hits to an unshielded hull damage",
				"vital ship systems and inflict casualties:",
				"• Disruptors: 100 - 400 hull damage.",
				"• Casualties deduct score (-1 per crew).",
				"• If life support fails, ship is lost.",
				"",
				"3. DAMAGE CONTROL & REPAIR RATES",
				"─────────────────────────────────────────",
				"Damage repairs proceed in stardates (SD).",
				"• In-flight repairs: 1.0x baseline pacing.",
				"• Starbase drydock: 4x accelerated pacing",
				"  (repairs proceed 4x faster at starbase).",
				"• Docking instantly clears damaged status",
				"  for devices given adequate stardates.",
			},
		},
		{
			ID:       "starbases",
			Number:   5,
			Title:    "Starbase Logistics & Surveillance",
			ShortTag: "[5] STARBASES",
			Lines: []string{
				"1. STARBASE DOCKING PROTOCOL",
				"─────────────────────────────────────────",
				"Starbases (>!<) are Starfleet supply hubs",
				"providing resupply and fleet maintenance.",
				"",
				"Docking Requirements:",
				"• Must maneuver to an adjacent sector",
				"  (distance <= 1.42 sector units).",
				"• Execute command: doc",
				"  (Or click starbase glyph on sector grid).",
				"• Shields lower automatically for mooring.",
				"",
				"2. LOGISTICAL SERVICING & RESTOCK",
				"─────────────────────────────────────────",
				"Upon successful mooring at a starbase:",
				"• Energy replenished to 5000 units.",
				"• Torpedo magazine restocked to 10.",
				"• Shield power transferred to main tank.",
				"• Accelerated 4x drydock repairs begin.",
				"",
				"3. SURVEILLANCE SENSOR NETWORKS",
				"─────────────────────────────────────────",
				"Starbase communication networks monitor",
				"hostile fleet movements across the galaxy:",
				"• FULL: All quadrant scans updated live.",
				"• CLASSIC: Starbases reveal their quadrant",
				"  and adjacent sector data on chart.",
				"• LOCAL: Only visited quadrants visible.",
				"• BLACKOUT: Sensor telemetry jammed;",
				"  Enterprise must scout manually.",
			},
		},
		{
			ID:       "tactics",
			Number:   6,
			Title:    "Tactical Threats & Enemy Doctrine",
			ShortTag: "[6] TACTICS",
			Lines: []string{
				"1. KLINGON BATTLE CRUISERS (+K+)",
				"─────────────────────────────────────────",
				"Standard Klingon warships in battle packs.",
				"• Energy: 300 - 500 units per cruiser.",
				"• Weapons: Disruptor beams and return fire.",
				"• Tactics: Converge on Enterprise when",
				"  shields weaken; coordinated barrage.",
				"",
				"2. KLINGON COMMANDERS (C) & CLOAKING",
				"─────────────────────────────────────────",
				"Elite command ships directing squadrons:",
				"• Cloaking Device: Invisible to SRS & LRS.",
				"• Cannot be locked by targeting computer.",
				"• Ambush: Fires disruptors while cloaked,",
				"  then maneuvers to evasive vector.",
				"• Decloaks when fired upon or damaged.",
				"",
				"3. SUPER-COMMANDERS (S)",
				"─────────────────────────────────────────",
				"Flagships coordinating planetary invasions",
				"and starbase sieges across quadrants:",
				"• Heavy shields & devastating firepower.",
				"• Orders wolfpacks to destroy starbases.",
				"• Top priority Starfleet target.",
				"",
				"4. ROMULAN WARBIRDS (R)",
				"─────────────────────────────────────────",
				"Patrol vessels along the Neutral Zone:",
				"• Armed with plasma torpedo technology.",
				"• Honorable combatants: May surrender when",
				"  heavily damaged (+1 point, zero loss).",
			},
		},
		{
			ID:       "scoring",
			Number:   7,
			Title:    "Scoring Engine & Starfleet Ranks",
			ShortTag: "[7] SCORING",
			Lines: []string{
				"1. AUTHENTIC 15-RULE SCORING ENGINE",
				"─────────────────────────────────────────",
				"Your final score is calculated from combat",
				"victories, efficiency, and mission losses:",
				"",
				"Combat Point Yields:",
				"• Standard Klingon:     +10 points",
				"• Klingon Commander:    +50 points",
				"• Super-Commander:     +200 points",
				"• Romulan Raider:       +20 points",
				"• Romulan Surrender:     +1 point",
				"",
				"Mission Victory Bonus:",
				"• 100 points * Skill Level (1 to 5)",
				"",
				"Efficiency Multiplier:",
				"• Kill Rate: 500 * (Kills / Stardates)",
				"  (Clamped to min 5.0 SD on defeat).",
				"",
				"2. PENALTIES & DEDUCTIONS",
				"─────────────────────────────────────────",
				"• Starbase Destroyed:  -100 points each",
				"• Distress Call Sent:   -45 points each",
				"• Planet Destroyed:     -10 points each",
				"• Star Destroyed:        -5 points each",
				"• Crew Casualty:         -1 point each",
				"• Starship Lost:       -200 points",
				"",
				"3. STARFLEET RANK TIERS",
				"─────────────────────────────────────────",
				"[DISHONOR]  Score < 0 (Court Martial)",
				"[ENS]       0 - 199      Ensign",
				"[LT]        200 - 499    Lieutenant",
				"[LCDR]      500 - 899    Lt. Commander",
				"[CDR]       900 - 1399   Commander",
				"[CAPT]      1400 - 1999  Captain",
				"[COMM]      2000 - 2799  Commodore",
				"[RADM]      2800 - 3999  Rear Admiral",
				"[VADM]      4000 - 4999  Vice Admiral",
				"[ADM]       5000 - 5999  Admiral",
				"[FADM]      6000+        Fleet Admiral",
			},
		},
		{
			ID:       "commands",
			Number:   8,
			Title:    "Command Reference & Keyboard Cheatsheet",
			ShortTag: "[8] COMMANDS",
			Lines: []string{
				"1. COMMAND LINE SYNTAX",
				"─────────────────────────────────────────",
				"Type commands in command bar at prompt:",
				"",
				"• nav <c> <w>     Warp vector flight",
				"• nav q <r> <c>   Jump to quadrant r,c",
				"• nav s <r> <c>   Move to sector r,c",
				"• tor <course>    Fire torpedo vector",
				"• tor <r> <c>     Fire torpedo at sector",
				"• pha <energy>    Fire phaser battery",
				"• she <units>     Transfer shield power",
				"• doc             Mooring at starbase",
				"• chart           Galactic chart map",
				"• dam             Damage status display",
				"• saves           Save/load browser",
				"• score           Hall of Fame & scores",
				"• opts            Game configuration",
				"• theme           Cycle visual theme",
				"• call            Starbase distress call",
				"• quit            Abandon mission",
				"",
				"2. HOTKEYS & SHORTCUTS",
				"─────────────────────────────────────────",
				"Direct single-key shortcuts when idle:",
				"• [F1] / [?]      Technical Manual",
				"• [F2]            Cycle Color Palette",
				"• [Ctrl+P]        Command Palette",
				"• [C] / [Ctrl+M]  Galactic Chart",
				"• [D]             Damage Schematic",
				"• [H]             Hall of Fame & Score",
				"• [O]             Options & Rules",
				"• [T]             Target Lock HUD",
				"• [Esc]           Dismiss Active Modal",
				"",
				"3. MOUSE INTERACTION",
				"─────────────────────────────────────────",
				"• Click Sector: Select navigation target",
				"• Click Enemy: Open Target-Lock HUD",
				"• Click Starbase: Dock automatically",
			},
		},
	}
}
